services:
  # Frontend React Application
  - type: web
    name: arbitrage-frontend
    env: static
    buildCommand: cd web/dashboard && npm ci && npm run build
    staticPublishPath: web/dashboard/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: arbitrage-backend
          property: host
      - key: VITE_WS_URL
        fromService:
          type: web
          name: arbitrage-backend
          property: host

  # Backend Python WebSocket Server
  - type: web
    name: arbitrage-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: cd web/dashboard/backend && pip install -r requirements.txt
    startCommand: cd web/dashboard/backend && python main.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      # Stellar Network Configuration
      - key: STELLAR_NETWORK
        value: TESTNET
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: STELLAR_SOROBAN_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: STELLAR_NETWORK_PASSPHRASE
        value: Test SDF Network ; September 2015
      
      # Contract IDs (update with your deployed addresses)
      - key: ARBITRAGE_DETECTOR_CONTRACT_ID
        sync: false
      - key: REFLECTOR_ORACLE_CONTRACT_ID
        sync: false
      - key: TRADING_ENGINE_CONTRACT_ID
        sync: false
      - key: FLASH_LOAN_ENGINE_CONTRACT_ID
        sync: false
      
      # Reflector Oracle API Configuration
      - key: REFLECTOR_API_URL
        value: https://api.reflector.network/v1
      - key: REFLECTOR_API_KEY
        sync: false
      - key: REFLECTOR_WS_URL
        value: wss://ws.reflector.network/v1
      
      # Server Configuration
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      
      # Security Configuration
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: arbitrage-frontend
          property: host
      
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: arbitrage-db
          property: connectionString
      
      # Logging Configuration
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: /tmp/arbitrage.log
      
      # Rate Limiting
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60
      
      # Simulation Parameters
      - key: NUM_ACCOUNTS
        value: 10
      - key: SIMULATION_INTERVAL
        value: 10
      - key: ARBITRAGE_SCAN_INTERVAL
        value: 15
      
      # Trading Parameters
      - key: MIN_PROFIT_THRESHOLD
        value: 0.01
      - key: MAX_TRADE_AMOUNT
        value: 1000
      - key: SLIPPAGE_TOLERANCE
        value: 0.005
      
      # Monitoring and Alerts
      - key: ENABLE_MONITORING
        value: true
      - key: ALERT_EMAIL
        sync: false
      - key: WEBHOOK_URL
        sync: false

  # Background Worker for Arbitrage Engine
  - type: worker
    name: arbitrage-worker
    env: python
    region: oregon
    plan: starter
    buildCommand: cd web/dashboard/backend && pip install -r requirements.txt
    startCommand: cd web/dashboard/backend && python arbitrage_engine.py
    envVars:
      # Inherit all environment variables from backend
      - key: STELLAR_NETWORK
        value: TESTNET
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: STELLAR_SOROBAN_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: STELLAR_NETWORK_PASSPHRASE
        value: Test SDF Network ; September 2015
      - key: ARBITRAGE_DETECTOR_CONTRACT_ID
        sync: false
      - key: REFLECTOR_ORACLE_CONTRACT_ID
        sync: false
      - key: TRADING_ENGINE_CONTRACT_ID
        sync: false
      - key: FLASH_LOAN_ENGINE_CONTRACT_ID
        sync: false
      - key: REFLECTOR_API_URL
        value: https://api.reflector.network/v1
      - key: REFLECTOR_API_KEY
        sync: false
      - key: NUM_ACCOUNTS
        value: 10
      - key: SIMULATION_INTERVAL
        value: 10
      - key: ARBITRAGE_SCAN_INTERVAL
        value: 15
      - key: MIN_PROFIT_THRESHOLD
        value: 0.01
      - key: MAX_TRADE_AMOUNT
        value: 1000
      - key: SLIPPAGE_TOLERANCE
        value: 0.005

databases:
  # PostgreSQL database for storing arbitrage data
  - name: arbitrage-db
    databaseName: arbitrage
    user: arbitrage_user
    region: oregon
    plan: starter

# Optional: Redis for caching and session management
  - name: arbitrage-redis
    plan: starter
    region: oregon